#
#
# Copyright 2016 The Symphony Software Foundation
#
# Licensed to The Symphony Software Foundation (SSF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# blocklist
# branches:
#  except:
#  - experimental

before_script: "if [[ \"$TRAVIS_PULL_REQUEST\" = \"false\" ]]; then curl -s https://raw.githubusercontent.com/symphonyoss/contrib-toolbox/master/scripts/download-files.sh | bash ; fi"

after_success: "if [[ \"$TRAVIS_PULL_REQUEST\" = \"false\" ]]; then curl -s https://raw.githubusercontent.com/symphonyoss/contrib-toolbox/master/scripts/oc-deploy.sh | bash ; fi"

language: java

install: true
script:
- "if [[ \"$TRAVIS_PULL_REQUEST\" = \"false\" && $TRAVIS_BRANCH =~ master ]]; then mvn clean deploy -Pintegration-testing,versioneye,whitesource,publish-site --settings settings.xml ; fi"
- "if [[ \"$TRAVIS_PULL_REQUEST\" = \"false\" && $TRAVIS_BRANCH =~ develop ]]; then mvn clean deploy -Pintegration-testing,whitesource --settings settings.xml ; fi"
- "if [[ \"$TRAVIS_PULL_REQUEST\" != \"false\" ]]; then mvn clean install ; fi"

jdk:
  - oraclejdk8

env:
  global:
   # Need to "gem install travis" first
   # Generated using command "travis encrypt COVERITY_SCAN_TOKEN="
   - secure: "TowBNPUOs/0hWq4myoZ/l99r3wjuwHdUhXFFm8YJ44eWQLojKXNKYIX6+L0byTGGEXjNS01HNb2hnMqNHZOJpe/ZtLu4k4NOIiPV/wfRfKC+kW3fftBEZEIAKoamqxF7gy7o4nz6zroPqKNq+y3Ug7qUCp2gcgGyLiQVB7o79l402QWtaxuUSyulJUc/cYR9bz/r810oSebGnrjM6KtKhdeQLNSQjwdw2+sztgehOkDO/Yc4Y5dMEgT4qo7wqPgp0Ti0riqivf5MGMnbhGTS2hJf8dmUMODrXh7q7nW2ThfPquE9ffBxHxW+zhXmnEr0UhTo6nEAveLVqPN1LD9la1m1dI4bIEKlMntCvpYTOsYjQl9MN+z1TYMU3EeZo4DBLyQ0SGRISSecNMAn21OMTY7t8hVAYeIJR4Y4P8b6vWElU3H3+29JOIXOraUqPiGDRhq9rnXDISHvQV7QIWV2uiwYkTCQgBSzgzIdWl3jVkfDnB3s6KrnVPyS1zEpj99EtNmEfHnEY3LSlKyd2W8P07djYftyQVVU3JQ//y4jbbh1mExlEU0d1Ja1LMOylOFHZ5adW64TNVi8CuxaQ9W0mqRDGOcWX1JfFk/MgJP48EndT0wI82d+BcBXPuYaC8DHUMAp//KwBeMxoUefvnm5q8XspEP8OIBoxXseRsBzFpg="
   # Generated using command "travis encrypt VERSIONEYE_API_KEY="
   - secure: "G/5nYf5iCCee7nptAc2ne4DICw9MBVB1TlGeUL31a8R1fQE8HG7yfcTSyYoRrTYZo2zwle9IYnvwLXKtHZLc3DBDQhTTA+nucGHgaEeG/93l+TrBa61TuGrpyRjn9TWrTEF3w79C/kcoAbUhJgYpWyQwcS43HDNTWii6w1XmeZD5/4UQyPsA73EF3R2cTefXKLV45XEMfWfhJ+T43r5AX3hQxKAM/JTTuppocnbmC1QrlX7jc0yl6dRLyMe+gtC4f1qHgdrPkOR9AOgoFDtwCjnKTbwpuOzuWFYBEzumImGoY2mm97OLlRPq5QhlO8RGnFQrP3slBjfS2QTrf1vkTJ04j+pPVsunXbS8Cpvw9uqv7rnmIaPnJD3Q1V1+8/NYi9cGGyrVHj0Oy0ZjI/58tjPV9dK+s5G1GOudAqzOPgEccicDb5+exPbcMAkiOd/2W2Ls0v7PTc76zrCGlAHvwRZr82UimRnRwtN3ADs2lRuGBY5p6qO+1XlDsT/OILAuDch9emVjztdb00JocFBMKe7OiowGI1okgnEz0c02COVKYC63uRqtdLVWseVuKEUYmQDGgQllnAZ3LIB6j9r4BLWiRlmg3PqRfj/hAOgTLAurxIo1d2Up1FgB3M4xdK03t4Pefj4zsu1xMZnDWd/QHnKk9HIPtm3IQPELreV1Pjs="
   # Basic Foundation Dev Pod endpoints (used below)
   - FOUNDATION_API_URL=https://foundation-dev-api.symphony.com
   - FOUNDATION_POD_URL=https://foundation-dev.symphony.com
   - SESSIONAUTH_URL=$FOUNDATION_API_URL/sessionauth
   - KEYAUTH_URL=$FOUNDATION_API_URL/keyauth
   - POD_URL=$FOUNDATION_POD_URL/pod
   - AGENT_URL=$FOUNDATION_POD_URL/agent
   # Used by RssBot
   - RSS_URL=https://twitrss.me/twitter_user_to_rss/?user=symphonyoss
   - RSS_LIMIT=3
   # Used by oc-deploy.sh for CD
   - OC_BINARY_FOLDER=./target/symphony-java-sample-bots-0.9.0-SNAPSHOT
   - OC_BUILD_CONFIG_NAME=echobot

notifications:
  webhooks: https://app.fossa.io/hooks/travisci

# Coverity scan can be enabled for demo purposes
# addons:
#   coverity_scan:
#     project:
#       name: "symphonyoss/symphony-java-sample-bots"
#       description: "Build submitted via Travis CI"
#     notification_email: maoo@symphony.foundation
#     build_command_prepend: "mvn clean"
#     build_command: "mvn package"
#     branch_pattern: master
